package voc

import "testing"

func TestReadAnnotation(t *testing.T) {
	res, err := ReadAnnotation([]byte(`
		<annotation>
			<folder>cut</folder>
			<filename>meter-001.png</filename>
			<path>/home/meter-001.png</path>
			<source>
				<database>Unknown</database>
			</source>
			<size>
				<width>665</width>
				<height>148</height>
				<depth>3</depth>
			</size>
			<segmented>0</segmented>
			<object>
				<name>0</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>51</xmin>
					<ymin>55</ymin>
					<xmax>87</xmax>
					<ymax>101</ymax>
				</bndbox>
			</object>
			<object>
				<name>0</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>126</xmin>
					<ymin>48</ymin>
					<xmax>162</xmax>
					<ymax>98</ymax>
				</bndbox>
			</object>
			<object>
				<name>0</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>202</xmin>
					<ymin>40</ymin>
					<xmax>236</xmax>
					<ymax>88</ymax>
				</bndbox>
			</object>
			<object>
				<name>1</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>281</xmin>
					<ymin>31</ymin>
					<xmax>307</xmax>
					<ymax>86</ymax>
				</bndbox>
			</object>
			<object>
				<name>4</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>352</xmin>
					<ymin>33</ymin>
					<xmax>386</xmax>
					<ymax>86</ymax>
				</bndbox>
			</object>
			<object>
				<name>3</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>429</xmin>
					<ymin>33</ymin>
					<xmax>459</xmax>
					<ymax>81</ymax>
				</bndbox>
			</object>
			<object>
				<name>9</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>504</xmin>
					<ymin>36</ymin>
					<xmax>537</xmax>
					<ymax>83</ymax>
				</bndbox>
			</object>
			<object>
				<name>6</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>585</xmin>
					<ymin>21</ymin>
					<xmax>615</xmax>
					<ymax>65</ymax>
				</bndbox>
			</object>
			<object>
				<name>7</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>587</xmin>
					<ymin>77</ymin>
					<xmax>612</xmax>
					<ymax>111</ymax>
				</bndbox>
			</object>
			<object>
				<name>digits</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>214</xmin>
					<ymin>103</ymin>
					<xmax>414</xmax>
					<ymax>121</ymax>
				</bndbox>
			</object>
			<object>
				<name>mantissa</name>
				<pose>Unspecified</pose>
				<truncated>0</truncated>
				<difficult>0</difficult>
				<bndbox>
					<xmin>414</xmin>
					<ymin>105</ymin>
					<xmax>563</xmax>
					<ymax>122</ymax>
				</bndbox>
			</object>
		</annotation>
	`))

	if err != nil {
		t.Fatal(err)
	}

	if len(res.Objects) != 11 {
		t.Fatal("read", len(res.Objects), "objects, instead of the expected 11")
	}
}
